#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    rightSensor,    sensorLineFollower)
#pragma config(Sensor, in2,    potentio,       sensorPotentiometer)
#pragma config(Sensor, in4,    middleSensor,   sensorLineFollower)
#pragma config(Sensor, in5,    leftSensor,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  button,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  sonarIN,        sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port2,           handMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, PIDControl, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!MAKE SURE TO CALIBRATE GLOBALS
//Globals
float rightAngle = 510;
int oneFoot = 500;
float ground = 500;
float outsideTape = 500;
float objTape = 500;
int threshold = 1800;
const int ARM_UP_POTENTIO = 750;
const int ARM_DOWN_POTENTIO = 800;
int isHolding = 0;
int isObstacleEncountered = 0;
int armThreshold = 0;
char rcvChar;
int box;


float driveControl(int distance, int encoder){
	return 0.8 * (distance - abs(encoder));
}

// Slow the turn as it approaches the desired distance/angle
float turnControl(int distance, int encoder){
	return 0.3 * (distance - encoder);
}

//Left turns are negative
void turn(float degrees, int power){
  resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);

  float angle = 515 * (degrees / 90);
  float speed = (power > 127) ? 127 : power;
  bool done = false;

  while((getMotorEncoder(leftMotor) < angle || getMotorEncoder(rightMotor) < angle) && !done){
  	float slowDown = turnControl(angle, getMotorEncoder(rightMotor));
  	speed = slowDown > speed ? speed : slowDown;

  	if(abs(getMotorEncoder(leftMotor)) > angle){
  			motor[leftMotor] = 0;
  	}
  	else{
  		motor[leftMotor] = speed;
  	}
  	if(abs(getMotorEncoder(rightMotor)) > angle){
  		motor[rightMotor] = 0;
  	}
  	else{
  		motor[rightMotor] = -speed;
  	}
  	done = (motor[rightMotor] == 0 && motor[leftMotor] == 0);
  }
  wait1Msec(500);
}

void driveBackwards() {
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	int i = 0;
	while(i < 6){
		motor[leftMotor] = -20;
		motor[rightMotor] = -20;
		wait1Msec(10);
	}
	// maintain speed while motor encoder counts are less that the distance
}

//Claw and arm logic

void openHand(){
	motor[handMotor] = 63;
	wait1Msec(500);
	motor[handMotor] = 0;
	isHolding = 0;
}

void closeHand(){
	motor[handMotor] = -63;
	wait1Msec(150);
	motor[handMotor] = 0;
	isHolding = 1;
}


void lowerArm(){
	int power;
  int potentiometer;

  isHolding = 0;
  power = 21;
  potentiometer = 1000;
  motor[armMotor] = power;
  while(SensorValue[potentio] < ARM_DOWN_POTENTIO){
  	motor[armMotor] = power;
  }
  wait1Msec(1000);
  motor[armMotor] = 0;
}

void raiseArm(){
  int power;
  int potentiometer;
	power = -31;
  motor[armMotor] = power;
	while(SensorValue[potentio] > ARM_UP_POTENTIO){
  	motor[armMotor] = power;
  }
  motor[armMotor] = 0;

}

/** drives the robot at a specified distance with the specified speed
 * negative distances move the robot backwards
 * sign of the speed seems to have no effect
 * drive(1, 50); // move forward 1 foot at 50 speed
 * drive(1, -50); // move forward 1 foot at 50 speed
 * drive(-1, 50); // move backwards 1 foot at 50 speed
 * drive(-1, -50); // move backwards 1 foot at 50 speed
 */
void drive(float feet, float speed) {
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	int distance = 500 * feet;
	moveMotorTarget(leftMotor, distance, speed, false);
	moveMotorTarget(rightMotor, distance, speed, false);
}

void followLines(){
	  while(true){
	    if(SensorValue(rightSensor) > threshold){
	      motor[leftMotor]  = 63;
	      motor[rightMotor] = 0;
	    }
	    if(SensorValue(middleSensor) > threshold){
	      motor[leftMotor]  = 63;
	      motor[rightMotor] = 63;
	    }
	    if(SensorValue(leftSensor) > threshold){
	      motor[leftMotor]  = 0;
	      motor[rightMotor] = 63;
	    }
  }
 }

//This thread will loop so long as the program is running
task userInput() {
	while(true){
 		rcvChar = getChar(uartOne);
 		wait1Msec(30);
 		switch(rcvChar) {
 			 case '1':
 				box = 1;
 				break;
 			case '2':
 				box = 0;
 				break;
 			case 'a':
 				writeDebugStreamLine("a");
 				break;
 			case 'b':
 				writeDebugStreamLine("b");
 				break;
 			case 'c':
 				writeDebugStreamLine("c");
 				break;
 			case 'd':
 				writeDebugStreamLine("d");
 				break;
 			case 'x':
 				writeDebugStreamLine("x");
				break;
			case 'r':
				writeDebugStreamLine("raise");
				raiseArm();
				break;
			case 'e':
				writeDebugStreamLine("lower");
				lowerArm();
				break;
 			default:
		}
	}
}
task frontCollisionStop() {
	while(true) {
		wait1Msec(100);
		if (SensorValue[sonarIN] < 15 && motor[rightMotor] > 0 && motor[leftMotor] > 0) {
			writeDebugStreamLine("Collision imminent! Stopping...");

			// if motors are going forward, set to 0, but if they are going backwards then allow to move
			motor[rightMotor] = 0;
			motor[leftMotor] = 0;
		}
	}
}

task main() {
	writeDebugStreamLine("VEX Robot is starting up.");
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	configureSerialPort(uartOne, uartUserControl);
	setBaudRate(uartOne, baudRate115200);

	startTask(frontCollisionStop);
	startTask(userInput);
	while(true){

	}
}
