#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lightSensor,    sensorNone)
#pragma config(Sensor, in2,    potentio,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  button,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  sonarIN,        sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port2,           handMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, PIDControl, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!MAKE SURE TO CALIBRATE GLOBALS
//Globals

float rightAngle = 510;

int oneFoot = 500;

//sensor value for driving

float floopr = 500;

//sensor value for tape/border

float outsideTape = 500;

float objTape = 500;


// Not sure why I made this, slows down a tiny bit towards the end of the distance

float driveControl(int distance, int encoder){

    return 0.8 * (distance - encoder);

}


// Slow the turn as it approaches the desired distance/angle

float turnControl(int distance, int encoder){
    return 0.3 * (distance - encoder);
}


//I think this turns left with negative
void turn(float degrees, int power){
  resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);

  float angle = 500 * (degrees / 90);
  float speed = (power > 127) ? 127 : power;
  bool done = false;

  while((getMotorEncoder(leftMotor) < angle || getMotorEncoder(rightMotor) < angle) && !done){
  	float slowDown = turnControl(angle, getMotorEncoder(rightMotor));
  	speed = slowDown > speed ? speed : slowDown;

  	if(abs(getMotorEncoder(leftMotor)) > angle){
  			motor[leftMotor] = 0;
  	}
  	else{
  		motor[leftMotor] = speed;
  	}
  	if(abs(getMotorEncoder(rightMotor)) > angle){
  		motor[rightMotor] = 0;
  	}
  	else{
  		motor[rightMotor] = -speed;
  	}
  	done = (motor[rightMotor] == 0 && motor[leftMotor] == 0);
  }
  wait1Msec(500);
}





// sonar reaction



// tape reaction

// // react based off of what sort of tape


// Drives forward with positive
void drive(float feet, float power){
  resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);
  float speed = power > 127 ? 127: power;
  int distance = oneFoot * feet;

  while(getMotorEncoder(rightMotor) < distance && getMotorEncoder(leftMotor) < distance){
      float slowDown = driveControl(distance, getMotorEncoder(rightMotor));
      speed = slowDown > speed ? speed : slowDown;
      if(getMotorEncoder(rightMotor) > distance){
          motor[rightMotor] = 0;
      }
      else{
          motor[leftMotor] = speed;
      }
         if(getMotorEncoder(leftMotor) > distance){
             motor[leftMotor] = 0;
         }
         else{
             motor[rightMotor] = speed;
         }
  }
  wait1Msec(500);
}

//each line sensor
//The logic within the sample program makes sense: it will be constantly adjusting slightly left or right, keeping it on the line
void followLine(){
	// The robot will follow the line either until it has reached the end or it detects the object
	wait1Msec(200);
    // sensor sees light:
    if(SensorValue(lightSensor) > 500){
      // counter-steer left:
      motor[leftMotor]  = 63;
      motor[rightMotor] = 0;
    }
    // sensor sees dark:
    else
    {
      // counter-steer right:
      motor[leftMotor]  = 0;
      motor[rightMotor] = 63;
    }
}

// Secs depends on how hard to grab the object (Longer time for tighter squeeze)
// Need to check if negative or postitive to open/close

void hand(float secs, bool open){
	if (open) {
   	motor[handMotor] = 63;
 	} else {
   	motor[handMotor] = -63;
	}
 	  wait1Msec(secs * 1000);
}

//Lift - whether to raise or drop arm
// Need to check if the -/+ power is correct in terms of raise/lower
void arm(bool lift){
   int power;
   int potentiometer;

   if(lift){
       power = -31;
       potentiometer = 420;
       motor[armMotor] = power;
/*       if(SensorValue(sensorPotentiometer) > potentiometer){
           motor[armMotor] = power;
       }*/
          wait1Msec(1000);
   }
   else
   {
       power = 31;
       potentiometer = 1010;
       motor[armMotor] = power;
/*       if(SensorValue(sensorPotentiometer) < potentiometer){
           motor[armMotor] = power;
       }*/
          wait1Msec(500);
   }

}


// returns true if it detects something on sonar that can be picked up right in front of it
bool isDetectingNearObject() {
	return SensorValue(sonarIN) < 17 && SensorValue(sonarIN) > -1;
}

// returns true if it detects something on sonar but cannot reach it
bool isDetectingFarObject() {
	return SensorValue(sonarIN) > 17  && SensorValue(sonarIN) < 150 || SensorValue(sonarIN) == -1;
}

// pick up function
// Note: Port 2 is the hand and port 3 is the arm
void pickUp(){
	hand(0.50, true);
	arm(false);

	motor[leftMotor] = 31;
  motor[rightMotor] = 31;
  wait1Msec(600);
	hand(0.15, false);
	arm(true);
}

void putDown() {
	arm(false);
	hand(0.50, true);
	wait1Msec(600);
	motor[leftMotor] = -31;
	motor[rightMotor] = -31;

	arm(true);
	hand(0.15, false);
}

void stop() {
	motor[leftMotor] = 0;
  motor[rightMotor] = 0;
  motor[armMotor] = 0;
  motor[handMotor] = 0;
}



void resetMotors() {
	resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor)
}

int threshold = 1800;

struct Data {
	short sonarValue;
	short armValue;
	bool drive;
	bool armDown;
	bool clawClosed;
	int battery;
}

task main() {
    //Assume that the robot starts its journey facing the correct direction
    //What are we assuming about the arm?
    //robot drives forward until it finds the black line
	// StartTask(stopMotors);
		// bool isFirstLineFound
		resetMotors();
		configureSerialPort(uartOne, uartUserControl);
		setBaudRate(uartOne, baudRate115200);
		int rcvChar;
		while(true) {
			sendChar(uartOne, 'A');
			delay(250);
			sendChar(uartOne, 'B');
			delay(250);
			sendChar(uartOne, 'C');
			delay(250);
			sendChar(uartOne, 'D');
			delay(250);
			sendChar(uartOne, 'E');
			delay(250);
			sendChar(uartOne, 'F');
			delay(250);
			sendChar(uartOne, 'G');

			//	motor[leftMotor] = 50;
			//	motor[rightMotor] = 50;
		/*
			rcvChar = getChar(uartOne);
		 	if(rcvChar == -1) {
			  wait1Msec(3);
			  continue;
			}
			if (rcvChar == 1) {
				motor[leftMotor] = 50;
				motor[rightMotor] = 50;
				wait10Msec(5);
			}
			*/
		}




		// 1. drive forward to first line
		// do not want to specify a distance here so didn't use drive()
		// keep driving until detect black tape
/*
		while(SensorValue(lightSensor) < threshold) {
			motor[leftMotor] = 31;
			motor[rightMotor] = 31;
		}

		stop();

		// this is a right turn
		//motor[leftMotor] = 31;
		//motor[rightMotor]= -31;


		// search
		while(!isDetectingFarObject()) {
			motor[leftMotor] = -20;
			motor[rightMotor] = 20;
		}


		// approach

		// do the shuffle
		while(isDetectingFarObject()) {
			if (SensorValue(lightSensor) < threshold) {
				motor[leftMotor] = 0;
				motor[rightMotor] = 63;
			} else {
				motor[leftMotor] = 63;
				motor[rightMotor] = 0;
			}
		}

		// i dont know what im thinking
		// this does the same
		while(!isDetectingNearObject()) {
			if (SensorValue(lightSensor) < threshold) {
				motor[leftMotor] = 0;
				motor[rightMotor] = 63;
			} else {
				motor[leftMotor] = 63;
				motor[rightMotor] = 0;
			}
		}

		stop();

		pickUp();

		stop();

		turn(120, 31);

		stop();

		while(SensorValue(lightSensor) < threshold) {
			motor[leftMotor] = 31;
			motor[rightMotor] = 31;
		}
		stop();

		while(SensorValue(sonarIN) > 60) {
			if (SensorValue(lightSensor) < threshold) {
				motor[leftMotor] = 0;
				motor[rightMotor] = 63;
			} else {
				motor[leftMotor] = 63;
				motor[rightMotor] = 0;
			}
		}

		stop();

		putDown();
*/

}
