#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    rightSensor,    sensorLineFollower)
#pragma config(Sensor, in2,    potentio,       sensorPotentiometer)
#pragma config(Sensor, in4,    middleSensor,   sensorLineFollower)
#pragma config(Sensor, in5,    leftSensor,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  button,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  sonarIN,        sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port2,           handMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, PIDControl, driveRight, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!MAKE SURE TO CALIBRATE GLOBALS
//Globals
float rightAngle = 510;
int oneFoot = 500;
//sensor value for driving
float ground= 500;
//sensor value for tape/border
float outsideTape = 500;
float objTape = 500;
int threshold = 1800;

//Non-autonomous logic

// Not sure why I made this, slows down a tiny bit towards the end of the distance
float driveControl(int distance, int encoder){
	return 0.8 * (distance - abs(encoder));
}

// Slow the turn as it approaches the desired distance/angle
float turnControl(int distance, int encoder){
	return 0.3 * (distance - encoder);
}

//Left turns are negative
void turn(float degrees, int power){
  resetMotorEncoder(leftMotor);
  resetMotorEncoder(rightMotor);

  float angle = 515 * (degrees / 90);
  float speed = (power > 127) ? 127 : power;
  bool done = false;

  while((getMotorEncoder(leftMotor) < angle || getMotorEncoder(rightMotor) < angle) && !done){
  	float slowDown = turnControl(angle, getMotorEncoder(rightMotor));
  	speed = slowDown > speed ? speed : slowDown;

  	if(abs(getMotorEncoder(leftMotor)) > angle){
  			motor[leftMotor] = 0;
  	}
  	else{
  		motor[leftMotor] = speed;
  	}
  	if(abs(getMotorEncoder(rightMotor)) > angle){
  		motor[rightMotor] = 0;
  	}
  	else{
  		motor[rightMotor] = -speed;
  	}
  	done = (motor[rightMotor] == 0 && motor[leftMotor] == 0);
  }
  wait1Msec(500);
}

void driveBackwards() {
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);

	int i = 0;
	while(i < 6){
		motor[leftMotor] = -20;
		motor[rightMotor] = -20;
		wait1Msec(10);
	}
	// maintain speed while motor encoder counts are less that the distance
}


// Autonomous Logic

void avoidLines(){
	if(SensorValue(rightSensor) > threshold){
		turn(40, -40);
	}
	else if(SensorValue(leftSensor) > threshold){
		turn(40, 40);
	}
	else if(SensorValue(middleSensor) > threshold){
		driveBackwards();
	}
	wait1Msec(10);
}



//Claw and arm logic

void openHand(){
	motor[handMotor] = 63;
	wait1Msec(1000);
}

void closeHand(){
	motor[handMotor] = -63;
	wait1Msec(1000);
}



void lowerArm(){
	int power;
  int potentiometer;

  power = -31;
  potentiometer = 420;
  motor[armMotor] = power;
	if(SensorValue(sensorPotentiometer) > potentiometer){
  	motor[armMotor] = power;
  }
  wait1Msec(1000);
 }

void raiseArm(){
  int power;
  int potentiometer;

	power = 31;
  potentiometer = 1010;
  motor[armMotor] = power;
	if(SensorValue(sensorPotentiometer) < potentiometer){
  	motor[armMotor] = power;
  }
  wait1Msec(500);
}

/** drives the robot at a specified distance with the specified speed
 *nnegative distances move the robot backwards
 *nsign of the speed seems to have no effect
 *ndrive(1, 50); // move forward 1 foot at 50 speed
 *ndrive(1, -50); // move forward 1 foot at 50 speed
 *ndrive(-1, 50); // move backwards 1 foot at 50 speed
 *drive(-1, -50); // move backwards 1 foot at 50 speed
 */
void drive(float feet, float speed) {
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	int distance = 500 * feet;
	moveMotorTarget(leftMotor, distance, speed, false);
	moveMotorTarget(rightMotor, distance, speed, false);
}

//This thread will loop so long as the program is running
task UARTRx() {
 	while(true){
		char rcvChar;
  	rcvChar = getChar(uartOne);
  	wait1Msec(30);

		switch(rcvChar){
			case 'w':
				// forward
				writeDebugStreamLine("Drive forward.");
//				driveForward(1, 50);
				drive(1, 50);
				break;

			case 'a':
			  // turn left
				writeDebugStreamLine("Turn left.");
				turn(90, -50);
				break;

			case 's':
				// backward
				writeDebugStreamLine("Drive backwards.");
//				driveBackwards();
				drive(-1, 50);
				break;

			case 'd':
				// turn right
				writeDebugStreamLine("Turn right.");
				turn(90, 50);
				break;

			case 'e':
				// Lowers arm
				writeDebugStreamLine("Lower arm.");
				lowerArm();
				break;

			case 'r':
				// Raises arm
				writeDebugStreamLine("Raise arm.");
				raiseArm();
				break;

			case 'f':
				//opens claw
				writeDebugStreamLine("Open hand.");
				openHand();
				break;

			case 'g':
				writeDebugStreamLine("Close hand.");
				closeHand();
				break;

			default:
		}
	}
}

task main() {
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightMotor);
	wait1Msec(3000);

	configureSerialPort(uartOne, uartUserControl);
	setBaudRate(uartOne, baudRate115200);
	startTask(avoidLines());
	startTask(UARTRx);

	while(true){

	}
}
