#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    lightSensor,    sensorNone)
#pragma config(Sensor, in2,    potentio,       sensorPotentiometer)
#pragma config(Sensor, dgtl1,  button,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  sonarIN,        sensorSONAR_cm)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           leftMotor,     tmotorVex393_HBridge, PIDControl, reversed, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port2,           handMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           armMotor,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightMotor,    tmotorVex393_HBridge, PIDControl, driveRight, encoderPort, I2C_1)

//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//!!MAKE SURE TO CALIBRATE GLOBALS
//Globals
float rightAngle = 510;
int oneFoot = 500;

//sensor value for driving
float ground= 500;

//sensor value for tape/border
float outsideTape = 500;
float objTape = 500;

int threshold = 1800;

//Globals for data transmission
char rcvChar;
bool run;

struct Data {
	short sonarValue;
	short armValue;
	bool drive;
	bool armDown;
	bool clawClosed;
	int battery;
}


task UARTRx() {
  char rcvChar = 'f';
	while(1){
		wait1Msec(500);
  	rcvChar = getChar(uartOne);
		wait1Msec(50);
		switch(rcvChar){
			case 'w':
				writeDebugStreamLine("This is the buffer value: %c", rcvChar);
				break;
			case 'a':
				writeDebugStreamLine("This is the buffer value: %c", rcvChar);
				break;
			case 's':
				writeDebugStreamLine("This is the buffer value: %c", rcvChar);
				break;
			case 'd':
				writeDebugStreamLine("This is the buffer value: %c", rcvChar);
				break;
			case 'e':
				writeDebugStreamLine("This is the buffer value: %c", rcvChar);
				break;
			case 'r':
				writeDebugStreamLine("This is the buffer value: %c", rcvChar);
				break;
			default:
				break;
		}
		}

}

task main() {
		configureSerialPort(uartOne, uartUserControl);
		setBaudRate(uartOne, baudRate115200);

		startTask(UARTRx);
		while(true){
		}

}
